YourWebsite/Controllers/QuanliController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YourWebsite.Services;
using System.IO;
using System.Web.Helpers;
using System.Globalization;

namespace YourWebsite.Controllers
{
    public class QuanliController : Controller
    {
        CategoryService _categoryService = new CategoryService();
        ProductService _productService = new ProductService();
        ImageService _imageService = new ImageService();
        NewsService _newsService = new NewsService();
        // GET: Quanli
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Category()
        {
            List<Category> allCategory = _categoryService.getAll();
            ViewBag.categories = allCategory;
            ViewBag.Error = TempData["error"];
            return View();
        }

        public ActionResult Product()
        {
            List<Category> allCategory = _categoryService.getAll();
            ViewBag.categories = allCategory;
            List<Product> allProduct = _productService.getAll();
            ViewBag.products = allProduct;
            ViewBag.Error = TempData["error"];
            return View();
        }

        public ActionResult SliderManager()
        {
            List<Image> allImage = _imageService.getAll();
            ViewBag.images = allImage;
            ViewBag.Error = TempData["error"];
            return View();
        }

        public ActionResult ImageManager()
        {
            List<Image> allImage = _imageService.getAll();
            ViewBag.images = allImage;
            ViewBag.Error = TempData["error"];
            return View();
        }

        public ActionResult TrendImageManager()
        {
            List<Category> categories = _categoryService.getAll();
            ViewBag.categories = categories;
            List<Image> trendImages = _imageService.getImagesByNameCode(SLIMCONFIG.IS_TREND);
            ViewBag.trendImages = trendImages;
            ViewBag.Error = TempData["error"];
            return View();
        }

        public ActionResult News()
        {
            List<News> allNews = _newsService.getAll();
            ViewBag.allNews = allNews;
            ViewBag.Error = TempData["error"];
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult saveCategory(string id, string categoryName, string preCateID)
        {
            ViewBag.Error = "";
            int _id = -1;
            int.TryParse(id, out _id);
            int _preCateID = -1;
            int.TryParse(preCateID, out _preCateID);

            if(categoryName == null || categoryName.Equals(""))
            {
                ViewBag.Error += "Error: Không có tên Category!";
            }
            if (!"".Equals(ViewBag.Error))
            {
                TempData["error"] = ViewBag.Error;
                return RedirectToAction("Category");
            }
            _categoryService.addCategory(_id, categoryName, _preCateID);

            return RedirectToAction("Category");
        }

        [HttpPost]
        [ValidateInput(false)]
        public string editSubCate(string id, string name)
        {
            ViewBag.Error = "";
            int _id = -1;
            if (id == null || id.Equals(""))
            {
                return "Error: ID không hợp lệ!";
            }
            else if (int.TryParse(id, out _id) == false)
            {
                return "Error: Lỗi khi parse ID";
            }
            if (name == null || name.Equals(""))
            {
                return "Error: Không có tên sub-category";
            }
            Category c = _categoryService.findByid(_id);
            if (c == null)
            {
                return "Error: Không tìm thấy Category yêu cầu!";
            }
            c.Name = name;
            _categoryService.addCategory(c.ID, c.Name, (int)c.PreCateID);
            return "success";
        }

        public Object getCategoryInfo(int cateID)
        {
            return JsonConvert.SerializeObject(_categoryService.findByid(cateID));
        }

        [HttpPost]
        public string deleteCategory(string id)
        {
            int _id = -1;
            if (id == null || id.Equals(""))
            {
                return "Error: ID không hợp lệ!";
            }
            else if(int.TryParse(id, out _id) == false)
            {
                return "Error: Lỗi khi parse ID";
            }
            Category c = _categoryService.findByid(_id);
            if (c == null)
            {
                return "Error: Không tìm thấy Category yêu cầu!";
            }
            _categoryService.delete(c);
            return "Success";
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult saveProduct(string id, string productName, string productPrice, string productCateID, string description,
            string quantity, HttpPostedFileBase productImg1, HttpPostedFileBase productImg2, HttpPostedFileBase productImg3, HttpPostedFileBase productImg4, string trend)
        {
            int _id = -1;
            double _productPrice = -1;
            int _productCateID = -1;
            int _quantity = -1;
            string filePath1 = "";
            string filePath2 = "";
            string filePath3 = "";
            string filePath4 = "";
            int _trend = SLIMCONFIG.IS_NOT_TREND;
            ViewBag.Error = "";

            if (id == null || id.Equals(""))
            {
                _id = -1;
            }
            else if (int.TryParse(id, out _id) == false)
            {
                ViewBag.Error += "Error: Không thể parse ProductID <br/>";
            }
            if (productName == null || productName.Equals(""))
            {
                ViewBag.Error += "Error: Không có tên sản phẩm <br/>";
            }
            //if (description == null || description.Equals(""))
            //{
            //    error += "Error: Không có mô tả sản phẩm";
            //}
            if (productPrice == null || productPrice.Equals(""))
            {
                _productPrice = 0;
            }
            else if (double.TryParse(productPrice, out _productPrice) == false)
            {
                ViewBag.Error += "Error: Không thể parse giá của sản phẩm <br/>";
            }
            if (productCateID == null || productCateID.Equals(""))
            {
                _productCateID = -1;
            }
            else if (int.TryParse(productCateID, out _productCateID) == false)
            {
                ViewBag.Error += "Error: Không thể parse cateID của sản phẩm <br/>";
            }
            if (quantity == null || quantity.Equals(""))
            {
                _quantity = 0;
            }
            else if (int.TryParse(quantity, out _quantity) == false)
            {
                ViewBag.Error += "Error: Không thể parse quantity của sản phẩm <br/>";
            }
            if (trend == null || trend.Equals(""))
            {
                _trend = SLIMCONFIG.IS_NOT_TREND;
            }
            else if (int.TryParse(trend, out _trend) == false)
            {
                ViewBag.Error += "Error: Không thể parse Trend <br/>";
            }

            //check image
            if (productImg1 == null && productImg2 == null && productImg3 == null && _productService.isProductHasImage(_id) == false)
            {
                ViewBag.Error += "Bạn chưa chọn hình ảnh cho sản phẩm, xin hãy chọn ít nhất 1 hình";
            }
            else
            {

                if (productImg1 != null && productImg1.FileName != null)
                {

                    string newPath = Server.MapPath(SLIMCONFIG.path + "ProductImages");
                    string newPathBig = Server.MapPath(SLIMCONFIG.BIG_IMG_PATH + "ProductImages");
                    if (!Directory.Exists(newPath))
                    {
                        System.IO.Directory.CreateDirectory(newPath);
                    }
                    if (!Directory.Exists(newPathBig))
                    {
                        System.IO.Directory.CreateDirectory(newPathBig);
                    }
                    WebImage imgBig = _imageService.reSizeImgBig(productImg1);
                    imgBig.FileName = productImg1.FileName;
                    imgBig.Save(newPathBig + "/" + imgBig.FileName);


                    WebImage img = _imageService.reSizeImg(imgBig);
                    img.FileName = productImg1.FileName;
                    img.Save(newPath + "/" + img.FileName);
                    //productImg1.SaveAs(newPath + "/" + productImg1.FileName);
                    filePath1 = "/Images/" + "ProductImages/" + productImg1.FileName;
                }
                else
                {
                    //ViewBag.Error += "Thiếu hình ảnh 1 <br/>";
                }
                if (productImg2 != null && productImg2.FileName != null)
                {
                    string newPath = Server.MapPath(SLIMCONFIG.path + "ProductImages");
                    string newPathBig = Server.MapPath(SLIMCONFIG.BIG_IMG_PATH + "ProductImages");
                    if (!Directory.Exists(newPath))
                    {
                        System.IO.Directory.CreateDirectory(newPath);
                    }
                    if (!Directory.Exists(newPathBig))
                    {
                        System.IO.Directory.CreateDirectory(newPathBig);
                    }
                    WebImage imgBig = _imageService.reSizeImgBig(productImg2);
                    imgBig.FileName = productImg2.FileName;
                    imgBig.Save(newPathBig + "/" + imgBig.FileName);


                    WebImage img = _imageService.reSizeImg(imgBig);
                    img.FileName = productImg2.FileName;

YourWebsite/Views/Quanli/Category.cshtml
@{
    ViewBag.Title = "Category";
    List<Category> categories = ViewBag.categories;
}


<div class="container">
    @{
        if (!"".Equals(ViewBag.Error))
        {
            <div class="alert alert-danger">
                <strong>@Html.Raw(ViewBag.Error)</strong>
            </div>
        }

    }
    <div class="col-md-4">
        <h2>Thêm Category mới</h2>
        @using (Html.BeginForm("saveCategory", "Quanli", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input id="id" name="id" class="form-control" type="hidden" />
            <label>Tên Category</label>
            <input id="categoryName" name="categoryName" class="form-control" />
            <input id="preCateID" name="preCateID" class="form-control" value="@SLIMCONFIG.NONE_PRE_CATEGORY"  type="hidden"/>
                
            <input id="btnAddCategory" type="submit" class="btn btn-success" value="Add" />
            }
    </div>
    <div class="col-md-8">
        <table class="table" id="categoryTable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Category Name</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @{
                    for(int i = 0; i < categories.Count; i++)
                    {
                        Category c = categories.ElementAt(i);
                        if (c.PreCateID == SLIMCONFIG.NONE_PRE_CATEGORY)
                        {
                            <tr>
                                <td>@c.ID</td>
                                <td>@c.Name</td>
                                <td><button class="btn btn-warning" onclick="editCategory(@c.ID)">Edit</button></td>
                                <td><button class="btn btn-danger" onclick="deleteCategory(@c.ID)">Delete</button></td>
                                <td>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td></td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{
                                                for (int j = 0; j < categories.Count; j++)
                                                {
                                                    Category sc = categories.ElementAt(j);
                                                    if (sc.PreCateID == c.ID)
                                                    {
                                                        <tr>
                                                            <td><input id="subCateName+@sc.ID" class="form-control" disabled="disabled" value="@sc.Name" /></td>
                                                            <td><button id="btnEditSubCate+@sc.ID" class="btn btn-warning" onclick="editSubCategory(@sc.ID)">Edit</button></td>
                                                            <td><button class="btn btn-danger" onclick="deleteCategory(@sc.ID)">Delete</button></td>
                                                        </tr>
                                                    }
                                                }
                                                <tr>
                                                    @using (Html.BeginForm("saveCategory", "Quanli", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                                    {
                                                        <td hidden="hidden"><input class="form-control" id="subCateID" name="id" /></td>
                                                        <td hidden="hidden"><input class="form-control" id="SubPreID" name="preCateID" value="@c.ID" /></td>
                                                        <td><input id="subCategoryName" name="categoryName" class="form-control" placeholder="Tên sub-category" /></td>
                                                        <td><input id="btnAddSubCategory" type="submit" class="btn btn-success" value="Add" /></td>
                                                    }
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>

    </div>
</div>


<script>
    function editCategory(id)
    {
        $.ajax({
            url: "/Quanli/getCategoryInfo",
            data: {
                format: 'json',
                cateID: id,
            },
            error: function () {
                alert("Problem!")
            },
            success: function(data)
            {
                var cateObj = JSON.parse(data);
                $("#id").val(cateObj.ID);
                $("#categoryName").val(cateObj.Name);

                $("#btnAddCategory").val("Update");
            },
            type: 'GET'
        })
    }

    var editable = false;
    function editSubCategory(id)
    {
        if(editable == false)
        {
            var btn = document.getElementById("btnEditSubCate+"+id).firstChild;
            btn.data = btn.data = "Edit" ? "Update" : "Edit";
            var x = document.getElementById("subCateName+"+id).disabled = false;
            editable = true;
        }
        else
        {
            var subCateName = document.getElementById("subCateName+"+id).value;
            //alert(subCateName);
            $.ajax({
                url: "/Quanli/editSubCate",
                data: {
                    format: 'json',
                    id: id,
                    name: subCateName
                },
                error: function() {
                    alert("Problem");
                },
                success: function(data) {
                    if (data === "success")
                    {
                        
                        editable = false;
                        var x = document.getElementById("subCateName+" + id).disabled = true;
                        location.href = location.href;
                    }
                },
                type: 'POST'
            })
        }
    }

    function deleteCategory(id)
    {
       $.ajax({
            url: "/Quanli/deleteCategory",
            data: {
                format: 'json',
                id: id
            },
            error: function () {
                alert("Problem!")
            },
            success: function(data)
            {
                if (data === "Success")
                {
                    location.href = location.href;
                }
            },
            type: 'POST'
        })
    }
</script>

YourWebsite/Views/Quanli/ImageManager.cshtml
@{
    ViewBag.Title = "Image Manager";
    List<Image> images = ViewBag.images;
}

<h2>ImageManager</h2>

<div class="container">
    @{
        if (!"".Equals(ViewBag.Error))
        {
            <div class="alert alert-danger">
                <strong>@Html.Raw(ViewBag.Error)</strong>
            </div>
        }

    }
    <div class="col-md-4">
        @using (Html.BeginForm("saveImg", "Quanli", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="hidden" name="id" id="id" class="form-control" />
            <label>Chọn chức năng của hình ảnh</label>
            <select class="form-control" id="nameCode" name="nameCode">
                <option value="@SLIMCONFIG.UNIDENTIFIED_IMAGE">Unidentified</option>
                <option value="@SLIMCONFIG.MENU_BACKGROUND_IMAGE">Menu Background Image</option>
                <option value="@SLIMCONFIG.SLIDER_IMAGE">Slider Image</option>
            </select>
            <label>Chọn hình ảnh</label>
            <input type="file" id="img" name="path" class="form-control" style="height:40px;" />
            <label>Mô tả cho hình ảnh</label>
            <input id="utility" name="utility" class="form-control" />
            <input type="submit" class="btn btn-primary" id="btnSaveImg" value="Add" />
        }
    </div>
    <div class="col-md-8">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Type</th>
                    <th>Mô tả</th>
                    <th>Thumbnail</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @{ 
                    for(int i = 0; i < images.Count; i++)
                    {
                        Image im = images.ElementAt(i);
                        <tr>
                            <td>@im.ID</td>
                            <td>@im.NameCode</td>
                            <td>@im.Utility</td>
                            <td><img src="@im.Path" /></td>
                            <td><button class="btn btn-warning" id="btnEdit" onclick="editImage(@im.ID)">Edit</button></td>
                            <td><button class="btn btn-danger" id="btnDelete" onclick="deleteImage(@im.ID)">Delete</button></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

<script>

    function editImage(id)
    {
        $.ajax({
            url: "/Quanli/getImageInfo",
            data: {
                format: 'json',
                id: id
            },
            error: function() {
                alert("Problem!");
            },
            success: function (data) {
                var imgObj = JSON.parse(data);

                $("#id").val(imgObj.ID);
                $("#nameCode").val(imgObj.NameCode);
                $("#utility").val(imgObj.Utility);
                $("#btnSaveImg").val("Update");
            }
        })
    }

    function deleteImage(id)
    {
        $.ajax({
            url: "/Quanli/deleteImage",
            data: {
                format: 'json',
                id: id
            },
            error: function () {
                alert("Problem!")
            },
            success: function (data) {
                if (data === "Success") {
                    location.href = location.href;
                }
            },
            type: 'POST'
        })
    }
</script>

YourWebsite/Views/Quanli/Index.cshtml
@{
    ViewBag.Title = "Quản lí YourShop - Admin only";
}


@Html.ActionLink("Quản lí Sản Phẩm", "Product", "Quanli", null, new { @class = "btn btn-success", @style = "font-family:serif" })
@Html.ActionLink("Quản lí Danh Mục", "Category", "Quanli", null, new { @class = "btn btn-success", @style = "font-family:serif" })
@Html.ActionLink("Quản lí Slider", "SliderManager", "Quanli", null, new { @class = "btn btn-success", @style = "font-family:serif" })
@Html.ActionLink("Quản lí Trend Images", "TrendImageManager", "Quanli", null, new { @class = "btn btn-success", @style = "font-family:serif" })
@Html.ActionLink("Quản lí Tin tức", "News", "Quanli", null, new { @class = "btn btn-success", @style = "font-family:serif" })
@*
    @Html.ActionLink("Quản lí Hình Ảnh", "ImageManager", "Quanli", null, new { @class = "btn btn-success", @style = "font-family:serif" })
*@

YourWebsite/Views/Quanli/News.cshtml
@{
    ViewBag.Title = "Quan lí tin tức";
    List<News> allNews = ViewBag.allNews;
}

<head>
    <script type="text/javascript" src="~/Content/ckeditor/ckeditor.js"></script>
</head>
<div class="container">
    @{
        if (!"".Equals(ViewBag.Error))
        {
            <div class="alert alert-danger">
                <strong>@Html.Raw(ViewBag.Error)</strong>
            </div>
        }

    }
    <div class="col-md-4">
        <h2>Thêm Tin tức mới</h2>
        @using (Html.BeginForm("saveNews", "Quanli", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input class="form-control" id="id" name="id" type="hidden" />
            <label>Tiêu đề</label>
            <input class="form-control" id="title" name="title" />
            
            @*<label>Ngày viết bài</label>
            <div>
                <input class="form-control" type="text" id="datepicker" name="publishDate">
            </div>*@
            <label>Popular</label>
            <select class="form-control" id="popular" name="popular">
                <option value="@SLIMCONFIG.NORMAL_NEWS">Không</option>
                <option value="@SLIMCONFIG.POPULAR_NEWS">Có</option>
            </select>
           
            <label>Thumbnail</label>
            <div>
                <input class="form-control" id="mainImage" name="mainImage" />
            </div>
            <label>Mô tả ngắn</label>
            <input class="form-control" id="shortDes" name="shortDes" />
            <label>Nội dung</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>


            <input type="submit" class="btn btn-success" id="btnAddNews" value="Add" />
                    }
    </div>
    <div class="col-md-8">
        <table class="table" id="newsTable">
            <thead>
                <tr>
                    <th hidden="hidden">ID</th>
                    <th>Tiêu đề</th>
                    <th>Thumnail</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @{
                    for (int i = 0; i < allNews.Count; i++)
                    {
                        News n = allNews.ElementAt(i);
                        <tr>
                            <td hidden="hidden">@n.ID</td>
                            <td>@n.Title</td>
                            <td><img src="@n.MainImage" style="height:100px;width:100px;" /></td>
                            <td><button style="margin-top:50px;" class="btn btn-warning" onclick="editNews(@n.ID)">Edit</button></td>
                            <td><button style="margin-top:50px;" class="btn btn-danger" onclick="deleteNews(@n.ID)">Delete</button></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    CKEDITOR.replace('content')
</script>
<script>
    function editNews(id)
    {
       $.ajax({
            url: "/Quanli/getNewsInfo",
            data: {
                format: 'json',
                newsID:id
            },
            error: function() {
                alert("Problem");
            },
            success: function (data) {
                var newsObj = JSON.parse(data);

                $("#id").val(newsObj.ID);
                $("#title").val(newsObj.Title);
                $("#popular").val(newsObj.Popular);
                $("#mainImage").val(newsObj.MainImage);
                $("#shortDes").val(newsObj.ShortDes);
                CKEDITOR.instances['content'].setData(newsObj.Content);
                $("#btnAddNews").val("Update");
            }
        })
    }

    function deleteNews(id) {
        $.ajax({
            url: "/Quanli/deleteNews",
            data: {
                format: 'json',
                newsID: id
            },
            error: function () {
                alert("Problem!")
            },
            success: function (data) {
                if (data === "Success") {
                    location.href = location.href;
                }
            },
            type: 'POST'
        })
    }
</script>

YourWebsite/Views/Quanli/Product.cshtml
@{
    ViewBag.Title = "Quản lí sản phẩm";
    List<Category> categories = ViewBag.categories;
    List<Product> products = ViewBag.products;
}

<head>
    <script type="text/javascript" src="~/Content/ckeditor/ckeditor.js"></script>
</head>

<div class="container">
    @{ 
        if (!"".Equals(ViewBag.Error))
        {
            <div class="alert alert-danger">
                <strong>@Html.Raw(ViewBag.Error)</strong>
            </div>
        }
        
    }
    <div class="col-md-4">
        <h2>Thêm sản phẩm mới</h2>
        @using (Html.BeginForm("saveProduct", "Quanli", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input class="form-control" id="id" name="id" type="hidden"/>
            <label>Tên sản phẩm</label>
            <input class="form-control" id="productName" name="productName" />
            <label>Giá sản phẩm</label>
            <input class="form-control" id="productPrice" name="productPrice" />
            <label>Category</label>
            <select class="form-control" name="productCateID" id="productCateID">
                @{ 
                    for (int i = 0; i < categories.Count; i++)
                    {
                        Category c = categories.ElementAt(i);
                        <option value="@c.ID">@c.Name</option>
                    }
                }
            </select>
            <label>Trend</label>
            <select class="form-control" id="trend" name="trend">
                <option value="@SLIMCONFIG.IS_NOT_TREND">Không</option>
                <option value="@SLIMCONFIG.IS_TREND">Có</option>
            </select>
            <input type="hidden" class="form-control" id="quantity" name="quantity" />
            <label>Hình ảnh sản phẩm</label>
            <span>1.</span><input class="form-control" type="file" id="productImg1" name="productImg1" />
            <span>2.</span><input class="form-control" type="file" id="productImg2" name="productImg2" />
            <span>3.</span><input class="form-control" type="file" id="productImg3" name="productImg3" />
            <div hidden="hidden">
                <input class="form-control" type="file" id="productImg4" name="productImg4" />
            </div>
            <br/>
            <label>Description</label>
            <textarea name="description" id="description" class="form-control" rows="10"></textarea>
         
            
            <input type="submit" class="btn btn-success" id="btnAddProduct" value="Add" />
                    }
    </div>
    <div class="col-md-8">
        <table class="table" id="productTable">
            <thead>
                <tr>
                    <th hidden="hidden">ID</th>
                    <th>Tên sản phẩm</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @{ 
                    for (int i = 0; i < products.Count; i++)
                    {
                        Product p = products.ElementAt(i);
                        <tr>
                            <td hidden="hidden">@p.ID</td>
                            <td>@p.Name</td>
                            <td>@p.Price</td>
                            <td>@p.Quantity</td>
                            <td rowspan="2"><button style="margin-top:50px;" class="btn btn-warning" onclick="editProduct(@p.ID)">Edit</button></td>
                            <td rowspan="2"><button style="margin-top:50px;" class="btn btn-danger" onclick="deleteProduct(@p.ID)">Delete</button></td>

                        </tr>
                        <tr>
                            <td colspan="3">
                                <span>1.</span><img src="@p.Img1" style="height:100px;width:100px;"/>
                                <span>2.</span><img src="@p.Img2" style="height:100px;width:100px;"/>
                                <span>3.</span><img src="@p.Img3" style="height:100px;width:100px;"/>
                                @*<img src="@p.Img4" style="height:100px;width:100px;"/>*@
                            </td>
                            
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<script>
                CKEDITOR.replace('description')
</script>

<script>
    function editProduct(id)
    {
       $.ajax({
            url: "/Quanli/getProductInfo",
            data: {
                format: 'json',
                proId:id
            },
            error: function() {
                alert("Problem");
            },
            success: function (data) {
                var proObj = JSON.parse(data);

                $("#id").val(proObj.ID);
                $("#productName").val(proObj.Name);
                $("#productPrice").val(proObj.Price);
                $("#productCateID").val(proObj.CateID);
                $("#quantity").val(proObj.Quantity);
                $("#trend").val(proObj.Trend);
                CKEDITOR.instances['description'].setData(proObj.Descriptions);
                $("#btnAddProduct").val("Update");
            }
        })
    }

    function deleteProduct(id) {
        $.ajax({
            url: "/Quanli/deleteProduct",
            data: {
                format: 'json',
                proId: id
            },
            error: function () {
                alert("Problem!")
            },
            success: function (data) {
                if (data === "Success") {
                    location.href = location.href;
                }
            },
            type: 'POST'
        })
    }
</script>